import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { loadLeaguePlayers, type LeagueCode } from "../../lib/player-directory";
export const revalidate = 1800;
type Props = { params: Promise<{ league: string }> };
const valid = (value: string): value is LeagueCode => ["kbo", "mlb", "npb"].includes(value);
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { league } = await params; if (!valid(league)) return {}; const upper = league.toUpperCase(); return { title: `${upper} 투수·타자 전체 기록 | 장군 AI`, description: `${upper} 전체 선수의 시즌 타격·투구 기록을 구단별로 확인하세요.`, alternates: { canonical: `/players/${league}` } }; }
export default async function LeaguePlayersPage({ params }: Props) { const { league } = await params; if (!valid(league)) notFound(); const players = await loadLeaguePlayers(league); const teams = Map.groupBy(players, (player) => player.team); return <main className="min-h-screen bg-slate-950 px-5 py-12 text-white"><div className="mx-auto max-w-7xl"><Link href="/players" className="font-bold text-blue-400">← 전체 리그</Link><header className="mt-5 rounded-3xl border border-blue-500/30 bg-slate-900 p-8"><h1 className="text-4xl font-black">{league.toUpperCase()} 선수 기록</h1><p className="mt-3 text-slate-300">투수와 타자 총 {players.length}명 · 시즌 공식 기록 자동 갱신</p></header><div className="mt-8 grid gap-7">{[...teams.entries()].map(([team, roster]) => <section key={team} className="rounded-2xl border border-slate-800 bg-slate-900 p-5 md:p-7"><div className="flex items-end justify-between"><h2 className="text-2xl font-black">{team}</h2><span className="text-sm text-slate-400">{roster.length}명</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{roster.sort((a,b) => a.role.localeCompare(b.role) || b.games-a.games).map((player) => <Link key={`${player.role}-${player.id}`} href={`/player/${league}/${player.id}`} className="rounded-xl border border-slate-800 bg-slate-950 p-4 hover:border-blue-500"><div className="flex justify-between gap-2"><strong>{player.name}</strong><span className="text-xs font-bold text-blue-400">{player.role}</span></div><p className="mt-2 text-xs text-slate-500">{player.games}경기 · 상세 기록 보기</p></Link>)}</div></section>)}</div></div></main>; }
