import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { loadPlayer, type LeagueCode, type PlayerRecord } from "../../../lib/player-directory";

export const revalidate = 1800;
type Props = { params: Promise<{ league: string; id: string }> };
const valid = (value: string): value is LeagueCode => ["kbo", "mlb", "npb"].includes(value);
async function getPlayer(params: Props["params"]) { const { league, id } = await params; return valid(league) ? loadPlayer(league, id) : null; }
function value(player: PlayerRecord, key: string) { return player.stats[key]; }
function playerSummary(player: PlayerRecord) { if (player.role.includes("투수")) return `${player.name}은(는) ${player.team} 소속 투수로 이번 시즌 ${value(player, "경기") ?? player.games}경기에 등판했습니다. 평균자책점은 ${value(player, "평균자책점") ?? "-"}, WHIP은 ${value(player, "WHIP") ?? "-"}이며 ${value(player, "이닝") ?? "-"}이닝 동안 탈삼진 ${value(player, "탈삼진") ?? 0}개를 기록하고 있습니다.`; return `${player.name}은(는) ${player.team} 소속 타자로 이번 시즌 ${value(player, "경기") ?? player.games}경기에 출전했습니다. 타율 ${value(player, "타율") ?? "-"}, 홈런 ${value(player, "홈런") ?? 0}개, 타점 ${value(player, "타점") ?? 0}개를 기록하고 있습니다.`; }

export async function generateMetadata({ params }: Props): Promise<Metadata> { const player = await getPlayer(params); if (!player) return { title: "선수 기록을 찾을 수 없습니다 | 장군 AI" }; const title = `${player.name} ${new Date().getFullYear()} 성적·기록 | ${player.league.toUpperCase()} 장군 AI`; const description = playerSummary(player); return { title, description, alternates: { canonical: `/player/${player.league}/${player.id}` }, openGraph: { title, description, type: "article" } }; }

export default async function PlayerPage({ params }: Props) { const player = await getPlayer(params); if (!player) notFound(); const jsonLd = { "@context": "https://schema.org", "@type": "Person", name: player.name, alternateName: player.originalName || undefined, url: `https://장군분석.kr/player/${player.league}/${player.id}`, affiliation: { "@type": "SportsTeam", name: player.team } }; return <main className="min-h-screen bg-slate-950 px-5 py-12 text-white"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><article className="mx-auto max-w-5xl"><Link href={`/players/${player.league}`} className="font-bold text-blue-400">← {player.league.toUpperCase()} 선수 목록</Link><header className="mt-5 rounded-3xl border border-blue-500/30 bg-slate-900 p-8 md:p-10"><p className="font-black text-blue-400">{player.league.toUpperCase()} · {player.team} · {player.role}</p><h1 className="mt-3 text-4xl font-black md:text-6xl">{player.name}</h1>{player.originalName && player.originalName !== player.name && <p className="mt-2 text-slate-500">{player.originalName}</p>}<p className="mt-4 text-slate-300">{new Date().getFullYear()} 정규시즌 기록 · 자동 갱신</p></header><section className="mt-7 rounded-2xl border border-slate-800 bg-slate-900 p-6 md:p-8"><h2 className="text-2xl font-black">시즌 {player.role} 성적</h2><p className="mt-4 leading-7 text-slate-300">{playerSummary(player)}</p><dl className="mt-6 grid grid-cols-2 gap-3 md:grid-cols-4">{Object.entries(player.stats).map(([label,statValue]) => <div key={label} className="rounded-xl bg-slate-950 p-4"><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-2 text-xl font-black">{statValue}</dd></div>)}</dl></section><section className="mt-7 grid gap-5 md:grid-cols-2"><div className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-xl font-black">기록을 보는 방법</h2><p className="mt-4 text-sm leading-7 text-slate-300">{player.role.includes("투수") ? "평균자책점은 9이닝당 자책점, WHIP은 이닝당 허용한 안타와 볼넷을 뜻합니다. 두 수치가 낮을수록 실점과 출루 억제력이 안정적이었다고 볼 수 있습니다." : "타율은 타수 대비 안타 비율, 출루율은 타석에서 살아 나간 비율, 장타율은 타수당 루타 생산력을 나타냅니다. OPS는 출루율과 장타율을 합친 공격 지표입니다."}</p></div><div className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-xl font-black">데이터 갱신 기준</h2><p className="mt-4 text-sm leading-7 text-slate-300">시즌 기록은 각 리그의 공개 기록을 정기적으로 확인해 반영합니다. 경기 종료 직후에는 공식 기록 정정이나 데이터 제공 시점에 따라 수치가 잠시 달라질 수 있습니다.</p></div></section><div className="mt-7 rounded-xl border border-slate-800 bg-slate-900 p-5 text-sm leading-6 text-slate-400"><p>이 페이지는 선수 기록을 이해하기 쉽게 정리한 정보 자료이며 경기 결과나 금전적 이익을 보장하지 않습니다.</p><a href={player.sourceUrl} target="_blank" rel="noreferrer" className="mt-3 inline-block font-bold text-blue-400">공식 선수 기록 확인 →</a></div></article></main>; }
