"use client";
import { useEffect,useState } from "react";

type Recent={date:string;opponent:string;result:string;score:string;competition:string};
type Standing={rank:number|null;points:number;played:number;wins:number;draws:number;losses:number;goalDifference:number}|null;
type Data={success:boolean;message?:string;home:string;away:string;homeRecent:Recent[];awayRecent:Recent[];h2h:Recent[];homeForm:any;awayForm:any;homeStanding:Standing;awayStanding:Standing;market:any;expert:{lean:string;goalView:string;confidence:string;reasons:string[];summary:string};source:string};

function RecentList({title,games}:{title:string;games:Recent[]}){return <section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="text-lg font-black">{title}</h2><div className="mt-4 space-y-3">{games.length?games.map((g,i)=><div key={`${g.date}-${i}`} className="grid grid-cols-[72px_32px_1fr_auto] items-center gap-2 border-b border-slate-800 pb-3 text-sm"><span className="text-slate-500">{g.date.slice(5)}</span><b className={g.result==="승"?"text-emerald-400":g.result==="패"?"text-rose-400":"text-amber-300"}>{g.result||"H2H"}</b><span>{g.opponent}</span><strong>{g.score}</strong></div>):<p className="text-sm text-slate-500">확인 가능한 최근 기록이 없습니다.</p>}</div></section>}
function Rank({name,data}:{name:string;data:Standing}){return <div className="rounded-xl border border-slate-800 bg-slate-950/60 p-4"><p className="font-black">{name}</p>{data?<div className="mt-3 grid grid-cols-3 gap-2 text-center text-sm"><div><b className="block text-xl text-emerald-400">{data.rank??"-"}</b>순위</div><div><b className="block text-xl">{data.points}</b>승점</div><div><b className="block text-xl">{data.goalDifference>0?`+${data.goalDifference}`:data.goalDifference}</b>득실차</div><div className="col-span-3 mt-2 text-slate-400">{data.played}경기 {data.wins}승 {data.draws}무 {data.losses}패</div></div>:<p className="mt-3 text-sm text-slate-500">시즌 순위 집계 전</p>}</div>}

export default function AnalysisClient({query}:{query:Record<string,string>}){const [data,setData]=useState<Data|null>(null),[error,setError]=useState("");useEffect(()=>{const p=new URLSearchParams(query);fetch(`/api/football/analysis?${p}`).then(r=>r.json()).then(x=>{if(!x.success)throw new Error(x.message);setData(x)}).catch(e=>setError(e.message||"분석을 불러오지 못했습니다."))},[query]);if(error)return <div className="mt-6 rounded-2xl border border-rose-900 bg-rose-950/30 p-6 text-rose-200">{error}</div>;if(!data)return <div className="mt-6 rounded-2xl border border-slate-800 bg-slate-900 p-10 text-center text-slate-400">상대전적과 최근 흐름을 분석 중입니다.</div>;
return <div className="mt-6 space-y-6"><section className="rounded-3xl border border-emerald-700/50 bg-gradient-to-br from-emerald-950/60 to-slate-900 p-6"><p className="text-xs font-black tracking-[.2em] text-emerald-400">AI EXPERT ANALYSIS</p><div className="mt-4 flex flex-wrap items-center gap-3"><h2 className="text-2xl font-black">{data.expert.lean}</h2><span className="rounded-full bg-slate-950 px-3 py-1 text-xs">판단 신뢰도 {data.expert.confidence}</span></div><p className="mt-4 leading-7 text-slate-200">{data.expert.summary}</p><ul className="mt-4 space-y-2 text-sm text-slate-400">{data.expert.reasons.map(x=><li key={x}>• {x}</li>)}</ul></section>
<section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="text-lg font-black">리그 순위 비교</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><Rank name={data.home} data={data.homeStanding}/><Rank name={data.away} data={data.awayStanding}/></div></section>
<div className="grid gap-5 md:grid-cols-2"><RecentList title={`${data.home} 최근 5경기`} games={data.homeRecent}/><RecentList title={`${data.away} 최근 5경기`} games={data.awayRecent}/></div>
<RecentList title="최근 상대전적" games={data.h2h}/>
<section className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="font-black">득점 흐름</h2><p className="mt-3 text-slate-300">{data.expert.goalView}</p><div className="mt-4 text-sm text-slate-400">{data.home} 평균 {data.homeForm.avgFor}득점 / {data.homeForm.avgAgainst}실점<br/>{data.away} 평균 {data.awayForm.avgFor}득점 / {data.awayForm.avgAgainst}실점</div></div><div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="font-black">시장 기준</h2>{data.market?<div className="mt-3 text-slate-300"><p>기준: {data.market.details??"확인 중"}</p><p>오버/언더: {data.market.overUnder??"확인 중"}</p><p className="mt-2 text-xs text-slate-500">{data.market.provider}</p></div>:<p className="mt-3 text-sm text-slate-500">현재 제공된 시장 기준이 없습니다.</p>}</div></section>
<p className="text-xs leading-5 text-slate-600">데이터 출처: {data.source}. 분석은 공개 기록을 수치화한 참고 정보이며 결과를 보장하지 않습니다.</p></div>}
