"use client";
import {useEffect,useState} from "react";

type Recent={date:string;opponent:string;result:string;score:string;competition:string;homeAway?:string;homeTeam?:string;awayTeam?:string;homeScore?:string;awayScore?:string};
type Form={games:number;win:number;draw:number;loss:number;winRate:number;avgFor:number;avgAgainst:number;goalDifference:number;cleanSheetRate:number;scorelessRate:number;over15Rate:number;over25Rate:number;over35Rate:number;under25Rate:number;under35Rate:number;bttsRate:number};
type Data={success:boolean;message?:string;home:string;away:string;homeRecent:Recent[];awayRecent:Recent[];h2h:Recent[];homeForm:Form;awayForm:Form;homeIndex:any;awayIndex:any;homeVenue:Form;awayVenue:Form;homeStanding:any;awayStanding:any;homeFatigue:any;awayFatigue:any;h2hStats:any;market:any;prediction:any;power:any;lean:string;keyPoints:string[];risks:string[];reliability:string;narrative:string[];attackAdvantage:string;defenseAdvantage:string;source:string};
const card="rounded-2xl border border-slate-800 bg-slate-900/70 p-5";
const rate=(v:number)=>`${v}%`;
const easyRisk=(text:string)=>text.replace("H2H 표본이 적어 상대전적의 예측 가중치를 낮췄습니다.","두 팀이 최근 직접 맞붙은 경기 자료가 적어, 과거 맞대결은 예상에 적게 반영했습니다.").replace("현재 시즌 순위 데이터가 완전하지 않습니다.","현재 시즌 순위 자료가 아직 충분하지 않습니다.").replace("시장 배당 데이터가 제공되지 않았습니다.","해외 배당업체의 예상 자료가 제공되지 않았습니다.").replace("최근 경기 데이터가 10경기보다 적은 팀이 있습니다.","최근 완료 경기 자료가 10경기보다 적은 팀이 있습니다.");
const easyText=(text:string)=>text.replace("양 팀 최근 경기 기준 O2.5 비율","양 팀의 최근 경기에서 두 팀 합계 3골 이상 나온 비율").replace("H2H 표본이 적어 상대전적의 예측 가중치를 낮췄습니다.","두 팀이 최근 직접 맞붙은 경기 자료가 적어서, 과거 맞대결 결과는 예상에 적게 반영했습니다.").replace("장군 모델","사이트 분석").replace("시장 홈승 평가","해외 배당업체의 홈팀 승리 예상").replace("모델 예상 득점","사이트 예상 득점").replace("모델은","사이트 분석은");

function RecentList({title,games,h2h=false}:{title:string;games:Recent[];h2h?:boolean}){return <section className={card}><h2 className="text-lg font-black">{title}</h2><p className="mt-1 text-xs text-slate-500">{h2h?"두 팀이 과거에 직접 맞붙은 경기입니다. 홈팀이 왼쪽, 원정팀이 오른쪽입니다.":"모든 경기에서 홈팀이 왼쪽, 원정팀이 오른쪽입니다."}</p><div className="mt-4 space-y-2">{games.length?games.map((g,i)=><div key={`${g.date}-${i}`} className="flex flex-wrap items-center gap-x-2 gap-y-1 border-b border-slate-800 pb-2 text-sm"><span className="w-12 text-slate-500">{g.date.slice(5)}</span><b className={g.result==="승"?"text-emerald-400":g.result==="패"?"text-rose-400":"text-amber-300"}>{g.result||(h2h?"맞대결":"무")}</b>{g.homeTeam&&g.awayTeam?<span className="font-bold"><span>{g.homeTeam}</span> <strong className="mx-1 text-white">{g.homeScore} : {g.awayScore}</strong> <span>{g.awayTeam}</span></span>:<span className="font-bold">{g.opponent} <strong className="ml-1 text-white">{g.score.replace("-"," : ")}</strong></span>}<span className="ml-auto text-xs text-slate-600">{g.competition}</span></div>):<p className="text-sm text-slate-500">확인 가능한 경기 기록이 없습니다.</p>}</div></section>}
function StatGrid({form}: {form:Form}){const stats=[["승/무/패",`${form.win}/${form.draw}/${form.loss}`],["승률",rate(form.winRate)],["평균 득점",form.avgFor],["평균 실점",form.avgAgainst],["득실차",form.goalDifference>0?`+${form.goalDifference}`:form.goalDifference],["무실점 경기",rate(form.cleanSheetRate)],["무득점 경기",rate(form.scorelessRate)],["3골 이상 경기",rate(form.over25Rate)],["2골 이하 경기",rate(form.under25Rate)],["양 팀 모두 득점",rate(form.bttsRate)]];return <div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-5">{stats.map(([k,v])=><div key={k} className="rounded-xl bg-slate-950/70 p-3 text-center"><b className="block text-base">{v}</b><span className="text-xs text-slate-500">{k}</span></div>)}</div>}
function TeamForm({name,form,index}:{name:string;form:Form;index:any}){return <div className="rounded-xl bg-slate-950/60 p-4"><div className="flex items-center justify-between"><b>{name}</b>{index&&<span className="font-black text-emerald-400">{index.score}/100 · {index.label}</span>}</div><StatGrid form={form}/></div>}
function FormComparison({home,away,homeForm,awayForm,homeIndex,awayIndex,title}:{home:string;away:string;homeForm:Form;awayForm:Form;homeIndex?:any;awayIndex?:any;title:string}){
  const rows=[
    {label:"승 · 무 · 패",home:`${homeForm.win}승 ${homeForm.draw}무 ${homeForm.loss}패`,away:`${awayForm.win}승 ${awayForm.draw}무 ${awayForm.loss}패`,hv:homeForm.winRate,av:awayForm.winRate},
    {label:"승률",home:`${homeForm.winRate}%`,away:`${awayForm.winRate}%`,hv:homeForm.winRate,av:awayForm.winRate},
    {label:"경기당 평균 득점",home:`${homeForm.avgFor}골`,away:`${awayForm.avgFor}골`,hv:homeForm.avgFor,av:awayForm.avgFor},
    {label:"경기당 평균 실점",home:`${homeForm.avgAgainst}골`,away:`${awayForm.avgAgainst}골`,hv:-homeForm.avgAgainst,av:-awayForm.avgAgainst},
    {label:"전체 득실차",home:homeForm.goalDifference>0?`+${homeForm.goalDifference}`:String(homeForm.goalDifference),away:awayForm.goalDifference>0?`+${awayForm.goalDifference}`:String(awayForm.goalDifference),hv:homeForm.goalDifference,av:awayForm.goalDifference},
    {label:"무실점 경기",home:`${homeForm.cleanSheetRate}%`,away:`${awayForm.cleanSheetRate}%`,hv:homeForm.cleanSheetRate,av:awayForm.cleanSheetRate},
    {label:"무득점 경기",home:`${homeForm.scorelessRate}%`,away:`${awayForm.scorelessRate}%`,hv:-homeForm.scorelessRate,av:-awayForm.scorelessRate},
    {label:"3골 이상 경기",home:`${homeForm.over25Rate}%`,away:`${awayForm.over25Rate}%`,hv:homeForm.over25Rate,av:awayForm.over25Rate,neutral:true},
    {label:"2골 이하 경기",home:`${homeForm.under25Rate}%`,away:`${awayForm.under25Rate}%`,hv:homeForm.under25Rate,av:awayForm.under25Rate,neutral:true},
    {label:"양 팀 모두 득점",home:`${homeForm.bttsRate}%`,away:`${awayForm.bttsRate}%`,hv:homeForm.bttsRate,av:awayForm.bttsRate,neutral:true},
  ];
  return <section className={card}><h2 className="text-lg font-black">{title}</h2><p className="mt-1 text-sm text-slate-500">같은 줄에서 두 팀 수치를 비교할 수 있습니다. 더 좋은 기록은 초록색으로 표시됩니다.</p><div className="mt-5 overflow-hidden rounded-2xl border border-slate-800"><div className="grid grid-cols-[1fr_110px_1fr] items-center bg-slate-950 p-4 text-center sm:grid-cols-[1fr_180px_1fr]"><div><b className="text-lg">{home}</b>{homeIndex&&<p className="mt-1 text-sm text-emerald-400">최근 폼 {homeIndex.score}점 · {homeIndex.label}</p>}</div><span className="text-xs font-bold text-slate-500">비교 항목</span><div><b className="text-lg">{away}</b>{awayIndex&&<p className="mt-1 text-sm text-emerald-400">최근 폼 {awayIndex.score}점 · {awayIndex.label}</p>}</div></div>{rows.map(r=>{const homeBest=!r.neutral&&r.hv>r.av,awayBest=!r.neutral&&r.av>r.hv;return <div key={r.label} className="grid grid-cols-[1fr_110px_1fr] items-center border-t border-slate-800 px-3 py-3 text-center sm:grid-cols-[1fr_180px_1fr]"><b className={homeBest?"text-emerald-400":"text-white"}>{homeBest&&<span className="mr-1">▲</span>}{r.home}</b><span className="text-xs text-slate-500 sm:text-sm">{r.label}</span><b className={awayBest?"text-emerald-400":"text-white"}>{r.away}{awayBest&&<span className="ml-1">▲</span>}</b></div>})}</div></section>
}
function Standing({name,data}:{name:string;data:any}){return <div className="rounded-xl bg-slate-950/60 p-4"><b>{name}</b>{data?<div className="mt-3 grid grid-cols-4 gap-2 text-center text-sm"><span><strong className="block text-lg">{data.rank??"-"}</strong>순위</span><span><strong className="block text-lg">{data.points}</strong>승점</span><span><strong className="block text-lg">{data.played}</strong>경기</span><span><strong className="block text-lg">{data.goalDifference>0?`+${data.goalDifference}`:data.goalDifference}</strong>득실차</span><p className="col-span-4 text-slate-400">{data.wins}승 {data.draws}무 {data.losses}패</p></div>:<p className="mt-3 text-sm text-slate-500">시즌 순위 데이터 없음</p>}</div>}
function Compare({data}:{data:Data}){return <div className="grid gap-4 md:grid-cols-2"><section className={card}><h2 className="font-black">공격력 비교</h2><div className="mt-4 grid grid-cols-[1fr_auto_1fr] gap-3 text-center"><b>{data.home}<strong className="mt-2 block text-2xl text-emerald-400">{data.homeForm.avgFor}</strong></b><span className="self-end pb-1 text-xs text-slate-500">평균 득점</span><b>{data.away}<strong className="mt-2 block text-2xl text-emerald-400">{data.awayForm.avgFor}</strong></b></div><p className="mt-4 text-center text-sm text-slate-400">우위: {data.attackAdvantage}</p></section><section className={card}><h2 className="font-black">수비력 비교</h2><div className="mt-4 grid grid-cols-[1fr_auto_1fr] gap-3 text-center"><b>{data.home}<strong className="mt-2 block text-2xl text-sky-400">{data.homeForm.avgAgainst}</strong></b><span className="self-end pb-1 text-xs text-slate-500">평균 실점</span><b>{data.away}<strong className="mt-2 block text-2xl text-sky-400">{data.awayForm.avgAgainst}</strong></b></div><p className="mt-4 text-center text-sm text-slate-400">우위: {data.defenseAdvantage}</p></section></div>}

export default function AnalysisClient({query}:{query:Record<string,string>}){const [data,setData]=useState<Data|null>(null),[error,setError]=useState("");useEffect(()=>{fetch(`/api/football/analysis?${new URLSearchParams(query)}`).then(r=>r.json()).then(x=>{if(!x.success)throw new Error(x.message);setData(x)}).catch(e=>setError(e.message||"분석을 불러오지 못했습니다."))},[query]);if(error)return <div className="mt-6 rounded-2xl border border-rose-900 bg-rose-950/30 p-6 text-rose-200">{error}</div>;if(!data)return <div className="mt-6 rounded-2xl border border-slate-800 bg-slate-900 p-10 text-center text-slate-400">최근 10경기와 상세 지표를 분석 중입니다.</div>;
const p=data.prediction,likely=p.probabilities.home>p.probabilities.away?data.home:p.probabilities.away>p.probabilities.home?data.away:"무승부",topScoreTotal=p.topScores.reduce((sum:number,x:any)=>sum+x.probability,0),outcomeCandidates=[{name:`${data.home} 승리`,probability:p.probabilities.home,description:`${data.home}이 경기에서 이길 확률입니다.`},{name:"무승부",probability:p.probabilities.draw,description:"두 팀이 비길 확률입니다."},{name:`${data.away} 승리`,probability:p.probabilities.away,description:`${data.away}이 경기에서 이길 확률입니다.`}].sort((a,b)=>b.probability-a.probability),bestOutcome=outcomeCandidates[0],otherCandidates=[{name:"두 팀 합계 3골 이상",probability:p.over25,description:"두 팀 점수를 합쳐 3골 이상 나오는 추천입니다."},{name:"두 팀 합계 2골 이하",probability:100-p.over25,description:"두 팀 점수를 합쳐 2골 이하로 끝나는 추천입니다."},{name:"양 팀 모두 득점",probability:p.btts,description:"두 팀이 각각 1골 이상 넣는 추천입니다."},{name:"한 팀 이상 무득점",probability:100-p.btts,description:"두 팀 중 적어도 한 팀이 득점하지 못하는 추천입니다."}],recommendedPicks=[...(bestOutcome.probability>=45?[bestOutcome]:[]),...otherCandidates.filter(x=>x.probability>=58).sort((a,b)=>b.probability-a.probability)].slice(0,3);return <div className="mt-6 space-y-6">
<section className="rounded-3xl border border-emerald-700/50 bg-gradient-to-br from-emerald-950/70 to-slate-900 p-6"><p className="text-xs font-black tracking-[.2em] text-emerald-400">장군 AI 경기 전망</p><div className="mt-3 flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-3xl font-black">{data.lean}</h2><p className="mt-2 text-sm text-slate-300">두 팀의 전력이 비슷한지, 어느 팀이 더 유리한지를 종합한 결론입니다.</p></div><span className="rounded-full bg-slate-950 px-3 py-1 text-sm">자료 충분도 {data.reliability}</span></div><div className="mt-6 grid gap-3 md:grid-cols-2 lg:grid-cols-5"><div className="rounded-xl bg-slate-950/50 p-3"><span className="text-xs text-slate-500">팀 전력 점수 · 100점 만점</span><b className="mt-1 block text-xl">{data.home} {data.power.home}점<br/>{data.away} {data.power.away}점</b></div><div className="rounded-xl bg-slate-950/50 p-3"><span className="text-xs text-slate-500">이길 가능성</span><b className="mt-1 block">{data.home} {p.probabilities.home}%<br/>무승부 {p.probabilities.draw}%<br/>{data.away} {p.probabilities.away}%</b><p className="mt-2 text-xs text-slate-400">가장 가능성이 큰 결과: {likely}</p></div><div className="rounded-xl bg-slate-950/50 p-3"><span className="text-xs text-slate-500">각 팀 예상 득점</span><b className="mt-1 block text-xl">{data.home} {p.expectedGoals.home}골<br/>{data.away} {p.expectedGoals.away}골</b></div><div className="rounded-xl bg-slate-950/50 p-3"><span className="text-xs text-slate-500">총 3골 이상 나올 가능성</span><b className="mt-1 block text-xl">{p.over25}%</b><p className="mt-2 text-xs text-slate-400">두 팀 득점 합계가 3골 이상일 확률입니다.</p></div><div className="rounded-xl bg-slate-950/50 p-3"><span className="text-xs text-slate-500">양 팀 모두 골을 넣을 가능성</span><b className="mt-1 block text-xl">{p.btts}%</b><p className="mt-2 text-xs text-slate-400">두 팀이 각각 1골 이상 넣을 확률입니다.</p></div></div></section>
<section className={card}><h2 className="text-lg font-black">경기 핵심 포인트</h2><ol className="mt-4 space-y-2 text-slate-300">{data.keyPoints.map((x,i)=><li key={x}><b className="mr-2 text-emerald-400">{i+1}</b>{easyText(x)}</li>)}</ol></section>
<section className="rounded-2xl border border-sky-700/60 bg-sky-950/20 p-5"><h2 className="text-lg font-black text-sky-300">추천 픽</h2><p className="mt-1 text-sm text-slate-400">승부 추천은 승리와 무승부를 합치지 않습니다. 홈승·무승부·원정승 중 가장 높은 결과를 그대로 표시합니다.</p>{bestOutcome.probability<45&&<p className="mt-4 rounded-xl border border-amber-800/50 bg-amber-950/20 p-4 text-sm text-amber-200">승패 추천 보류 · 가장 높은 결과가 {bestOutcome.name} {bestOutcome.probability}%로 확실한 우세가 아닙니다.</p>}{recommendedPicks.length?<div className="mt-4 grid gap-3 md:grid-cols-3">{recommendedPicks.map((pick,i)=><div key={pick.name} className="rounded-xl bg-slate-950/70 p-4"><span className="text-xs font-bold text-sky-400">추천 {i+1}</span><b className="mt-1 block text-lg">{pick.name}</b><strong className="mt-2 block text-2xl text-emerald-400">{pick.probability}%</strong><p className="mt-2 text-xs leading-5 text-slate-400">{pick.description}</p></div>)}</div>:<p className="mt-4 rounded-xl bg-slate-950/70 p-4 text-sm text-slate-300">확실하게 추천할 만큼 높은 수치가 없어 이번 경기는 추천을 보류합니다.</p>}<p className="mt-3 text-xs text-slate-600">추천 수치는 경기 결과를 보장하지 않으며 참고용입니다.</p></section>
<div className="grid gap-5 md:grid-cols-2"><RecentList title={`${data.home} 최근 ${data.homeRecent.length}경기`} games={data.homeRecent}/><RecentList title={`${data.away} 최근 ${data.awayRecent.length}경기`} games={data.awayRecent}/></div>
<FormComparison title="최근 10경기 한눈에 비교" home={data.home} away={data.away} homeForm={data.homeForm} awayForm={data.awayForm} homeIndex={data.homeIndex} awayIndex={data.awayIndex}/>
<FormComparison title="홈팀 홈 경기 vs 원정팀 원정 경기" home={`${data.home} 홈 (${data.homeVenue.games}경기)`} away={`${data.away} 원정 (${data.awayVenue.games}경기)`} homeForm={data.homeVenue} awayForm={data.awayVenue}/>
<Compare data={data}/>
<section className={card}><h2 className="text-lg font-black">경기에 몇 골이 나올까?</h2><p className="mt-1 text-sm text-slate-500">두 팀 득점 합계와 양 팀 득점 여부를 쉬운 말로 표시했습니다.</p><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-5">{[["총 2골 이상",Math.round((data.homeForm.over15Rate+data.awayForm.over15Rate)/2)],["총 3골 이상",p.over25],["총 4골 이상",Math.round((data.homeForm.over35Rate+data.awayForm.over35Rate)/2)],["총 2골 이하",100-p.over25],["양 팀 모두 1골 이상",p.btts]].map(([k,v])=><div key={k} className="rounded-xl bg-slate-950 p-4 text-center"><b className="text-xl">{v}%</b><span className="mt-1 block text-xs text-slate-400">{k}</span></div>)}</div><p className="mt-3 text-xs text-slate-500">예: ‘총 3골 이상 44%’는 2-1, 3-0, 2-2처럼 두 팀 점수를 합쳐 3골 이상일 가능성이 44%라는 뜻입니다.</p></section>
<section className={card}><h2 className="text-lg font-black">최근 맞대결</h2>{data.h2hStats.games>0&&<div className="mt-3 text-sm leading-7 text-slate-300">{data.home} {data.h2hStats.homeWins}승 · 무승부 {data.h2hStats.draws}경기 · {data.away} {data.h2hStats.awayWins}승<br/>한 경기 평균 총 {data.h2hStats.avgTotal}골 · 3골 이상 경기 {data.h2hStats.over25Rate}% · 양 팀 모두 득점한 경기 {data.h2hStats.bttsRate}%</div>}<div className="mt-4"><RecentList title={`맞대결 ${data.h2h.length}경기`} games={data.h2h} h2h/></div></section>
<section className={card}><h2 className="text-lg font-black">리그 / 시즌 전력</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><Standing name={data.home} data={data.homeStanding}/><Standing name={data.away} data={data.awayStanding}/></div></section>
{(data.homeFatigue||data.awayFatigue)&&<section className={card}><h2 className="text-lg font-black">일정 / 피로도</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{[[data.home,data.homeFatigue],[data.away,data.awayFatigue]].map(([name,f]:any)=>f&&<div key={name} className="rounded-xl bg-slate-950 p-4"><b>{name} · 피로도 {f.level}</b><p className="mt-2 text-sm text-slate-400">직전 경기 {f.lastDate} · 휴식 {f.restDays}일 · 최근 7일 {f.last7}경기 · 14일 {f.last14}경기</p></div>)}</div></section>}
{data.market&&<section className={card}><h2 className="text-lg font-black">해외 배당 예상과 사이트 분석 비교</h2><p className="mt-1 text-sm text-slate-500">해외 배당업체의 예상과 최근 경기 기록으로 계산한 사이트 예상을 나란히 비교합니다.</p><div className="mt-4 grid gap-4 md:grid-cols-2"><div className="rounded-xl bg-slate-950 p-4"><b>해외 배당업체 예상</b>{data.market.probabilities?<div className="mt-3 space-y-1 text-sm"><p>{data.home} 승리 <strong>{data.market.probabilities[0]}%</strong></p><p>무승부 <strong>{data.market.probabilities[1]}%</strong></p><p>{data.away} 승리 <strong>{data.market.probabilities[2]}%</strong></p></div>:<p className="mt-2 text-sm text-slate-400">승리 확률 정보가 없습니다.</p>}<p className="mt-3 text-xs text-slate-600">자료 제공: {data.market.provider??"해외 배당업체"}</p></div><div className="rounded-xl bg-slate-950 p-4"><b>최근 경기 기록으로 계산한 사이트 예상</b><div className="mt-3 space-y-1 text-sm"><p>{data.home} 승리 <strong>{p.probabilities.home}%</strong></p><p>무승부 <strong>{p.probabilities.draw}%</strong></p><p>{data.away} 승리 <strong>{p.probabilities.away}%</strong></p></div>{p.difference!=null&&<p className="mt-3 text-xs leading-5 text-slate-400">홈팀 승리 예상이 해외 배당업체보다 {Math.abs(p.difference)}%p {p.difference>=0?"높습니다":"낮습니다"}. 두 예상의 차이가 클수록 신중하게 판단해야 합니다.</p>}</div></div></section>}
{data.risks.length>0&&<section className="rounded-2xl border border-amber-900/60 bg-amber-950/20 p-5"><h2 className="font-black text-amber-300">이 예상을 볼 때 주의할 점</h2><ul className="mt-3 space-y-2 text-sm leading-6 text-amber-100/70">{data.risks.map(x=><li key={x}>• {easyRisk(x)}</li>)}</ul></section>}
<section className={card}><h2 className="text-lg font-black">AI 상세 분석</h2><div className="mt-4 space-y-3 leading-7 text-slate-300">{data.narrative.map((x,i)=><p key={i}>{easyText(x)}</p>)}</div></section>
<p className="text-xs leading-5 text-slate-600">데이터 출처: {data.source}. API에 없는 xG, 부상, 라인업, 슈팅 및 시간대 통계는 생성하지 않았습니다. 모델 예상 득점은 실제 xG가 아닌 최근 득실점 기반 Poisson 추정치입니다.</p>
</div>}
