"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import type { NewsArticle } from "../lib/news-types";
export default function NewsAdminClient(){const [secret,setSecret]=useState("");const [articles,setArticles]=useState<NewsArticle[]>([]);const [enabled,setEnabled]=useState(true);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);useEffect(()=>setSecret(sessionStorage.getItem("news-admin-secret")||""),[]);
 async function load(value=secret){setBusy(true);try{const r=await fetch("/api/admin/news",{headers:{"x-news-admin-secret":value},cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.message);sessionStorage.setItem("news-admin-secret",value);setArticles(j.articles||[]);setEnabled(j.enabled!==false);setMessage(`${j.articles?.length||0}개 기사를 불러왔습니다.`);}catch(e){setMessage(e instanceof Error?e.message:"조회 실패");}finally{setBusy(false);}}
 async function action(body:Record<string,unknown>){setBusy(true);try{const r=await fetch("/api/admin/news",{method:"POST",headers:{"Content-Type":"application/json","x-news-admin-secret":secret},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.message);setMessage(body.action==="generate"?(j.result?.reason||"새 기사를 생성했습니다."):"설정을 저장했습니다.");await load();}catch(e){setMessage(e instanceof Error?e.message:"작업 실패");setBusy(false);}}
 async function update(id:string,patch:Record<string,unknown>){if(patch.delete&&!confirm("이 기사를 삭제할까요?"))return;const r=await fetch(`/api/news/${id}`,{method:patch.delete?"DELETE":"PATCH",headers:{"Content-Type":"application/json","x-news-admin-secret":secret},body:patch.delete?undefined:JSON.stringify(patch)});const j=await r.json();setMessage(r.ok?"처리했습니다.":j.message);if(r.ok)await load();}
 return <main className="min-h-screen bg-slate-950 text-white"><header className="border-b border-slate-800"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5"><Link href="/" className="text-2xl font-black">장군 AI</Link><div className="flex gap-4 text-sm"><Link href="/admin-stats">경기 통계 관리</Link><Link href="/news">뉴스 보기</Link></div></div></header><section className="mx-auto max-w-6xl px-5 py-10"><p className="text-sm font-black text-cyan-400">OWNER ONLY</p><h1 className="mt-2 text-3xl font-black">스포츠 뉴스 관리</h1><div className="mt-6 flex flex-wrap gap-3"><input type="password" value={secret} onChange={e=>setSecret(e.target.value)} placeholder="NEWS_ADMIN_SECRET" className="min-w-64 rounded-xl border border-slate-700 bg-slate-900 px-4 py-3"/><button onClick={()=>load()} disabled={busy} className="rounded-xl bg-blue-600 px-5 py-3 font-black">목록 불러오기</button><button onClick={()=>action({action:"generate",status:"draft"})} disabled={busy} className="rounded-xl bg-cyan-600 px-5 py-3 font-black">뉴스 초안 1개 생성</button><button onClick={()=>action({action:"toggle",enabled:!enabled})} disabled={busy} className={`rounded-xl px-5 py-3 font-black ${enabled?"bg-emerald-600":"bg-slate-700"}`}>자동 생성 {enabled?"ON":"OFF"}</button></div>{message&&<p className="mt-4 text-sm text-slate-400">{message}</p>}<div className="mt-8 space-y-4">{articles.map(a=><article key={a.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div className="max-w-3xl"><p className="text-xs font-black text-cyan-400">{a.category} · {a.status}</p><h2 className="mt-2 text-lg font-black">{a.title}</h2><p className="mt-2 text-sm text-slate-400">{a.summary}</p></div><div className="flex flex-wrap gap-2"><Link href={`/news/${a.slug}`} target="_blank" className="rounded-lg border border-slate-700 px-3 py-2 text-sm">미리보기</Link>{a.status!=="published"&&<button onClick={()=>update(a.id,{status:"published",publishedAt:new Date().toISOString()})} className="rounded-lg bg-emerald-700 px-3 py-2 text-sm font-bold">발행</button>}{a.status!=="private"&&<button onClick={()=>update(a.id,{status:"private"})} className="rounded-lg bg-slate-700 px-3 py-2 text-sm">비공개</button>}<button onClick={()=>update(a.id,{delete:true})} className="rounded-lg bg-red-950 px-3 py-2 text-sm text-red-300">삭제</button></div></div><details className="mt-4"><summary className="cursor-pointer text-sm font-bold text-slate-400">제목·요약 수정</summary><EditForm article={a} save={patch=>update(a.id,patch)}/></details></article>)}</div></section></main>}
function EditForm({article,save}:{article:NewsArticle;save:(p:Record<string,unknown>)=>void}){const [title,setTitle]=useState(article.title);const [summary,setSummary]=useState(article.summary);return <div className="mt-4 grid gap-3"><input value={title} onChange={e=>setTitle(e.target.value)} className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2"/><textarea value={summary} onChange={e=>setSummary(e.target.value)} className="min-h-24 rounded-lg border border-slate-700 bg-slate-950 px-3 py-2"/><button onClick={()=>save({title,summary,seoTitle:title,seoDescription:summary})} className="w-fit rounded-lg bg-blue-700 px-4 py-2 text-sm font-bold">수정 저장</button></div>}
