import type { Metadata } from "next";
import Link from "next/link";
import { listNews } from "../lib/news-db";
import { NEWS_CATEGORIES, type NewsArticle } from "../lib/news-types";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title:"스포츠 뉴스", description:"KBO, MLB, NPB, 축구, NBA 주요 소식을 사실 중심으로 정리하고 장군분석의 데이터 해설을 더합니다.", alternates:{canonical:"/news"}, openGraph:{title:"장군분석 스포츠 뉴스",description:"오늘의 주요 스포츠 뉴스와 데이터 해설",url:"/news",type:"website"}, twitter:{card:"summary_large_image",title:"장군분석 스포츠 뉴스",description:"오늘의 주요 스포츠 뉴스와 데이터 해설"} };
function time(value:string){ return new Intl.DateTimeFormat("ko-KR",{timeZone:"Asia/Seoul",month:"long",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(value)); }
export default async function NewsPage({searchParams}:{searchParams:Promise<{category?:string}>}) {
  const {category="전체"}=await searchParams; let articles:NewsArticle[]=[]; let error="";
  try { articles=await listNews({status:"published",category,limit:60}); } catch(e){ error=e instanceof Error?e.message:"뉴스를 불러오지 못했습니다."; }
  return <main className="min-h-screen bg-slate-950 text-white"><header className="border-b border-slate-800 bg-slate-950/95"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5"><Link href="/" className="text-2xl font-black">장군 AI</Link><nav className="flex gap-4 text-sm font-bold"><Link href="/">야구</Link><Link href="/football">축구</Link><Link href="/news" className="text-cyan-400">뉴스</Link></nav></div></header><section className="mx-auto max-w-6xl px-5 py-12"><p className="text-sm font-black tracking-[.2em] text-cyan-400">JANGGUN SPORTS NEWS</p><h1 className="mt-3 text-4xl font-black md:text-5xl">오늘의 스포츠 뉴스</h1><p className="mt-4 max-w-3xl leading-7 text-slate-400">여러 공개 출처에서 확인되는 핵심 사실을 새롭게 정리하고, 경기력과 팀 전력에 미치는 영향을 알기 쉽게 설명합니다.</p><nav className="mt-8 flex gap-2 overflow-x-auto pb-2">{["전체",...NEWS_CATEGORIES].map(item=><Link key={item} href={item==="전체"?"/news":`/news?category=${encodeURIComponent(item)}`} className={`shrink-0 rounded-full px-4 py-2 text-sm font-black ${category===item?"bg-cyan-500 text-slate-950":"border border-slate-700 bg-slate-900 text-slate-300"}`}>{item}</Link>)}</nav>{error&&<div className="mt-8 rounded-2xl border border-amber-800 bg-amber-950/30 p-5 text-amber-200">{error}<p className="mt-2 text-sm">Supabase에서 뉴스 테이블 SQL을 먼저 실행해 주세요.</p></div>}{!error&&articles.length===0&&<div className="mt-10 rounded-3xl border border-slate-800 bg-slate-900 p-12 text-center text-slate-400">아직 발행된 뉴스가 없습니다.</div>}<div className="mt-8 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{articles.map(article=><article key={article.id} className="overflow-hidden rounded-3xl border border-slate-800 bg-slate-900"><img src={article.imageUrl} alt="" className="aspect-[16/9] w-full object-cover"/><div className="p-6"><div className="flex items-center justify-between text-xs"><span className="rounded-full bg-cyan-500/15 px-3 py-1 font-black text-cyan-300">{article.category}</span><span className="text-slate-500">{article.readingMinutes}분 읽기</span></div><h2 className="mt-4 text-xl font-black leading-8"><Link href={`/news/${article.slug}`} className="hover:text-cyan-300">{article.title}</Link></h2><p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-400">{article.summary}</p><p className="mt-5 text-xs text-slate-500">{time(article.publishedAt)}</p></div></article>)}</div></section></main>;
}
