"use client";
import Link from "next/link";import {Suspense,useEffect,useState} from "react";import {useSearchParams} from "next/navigation";
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5 md:p-6"><p className="text-sm font-black text-blue-400">{title}</p>{children}</section>}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-xl bg-slate-950 p-4"><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-2 text-lg font-black">{value}</p></div>}
function fmt(v:any,d=3){return typeof v==="number"&&Number.isFinite(v)?v.toFixed(d):"-"}
function PitcherTable({items}:{items:any[]}){return <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[560px] text-left text-sm"><thead className="text-xs text-slate-500"><tr><th className="py-2">선수</th><th>승-패</th><th>이닝</th><th>ERA</th><th>WHIP</th><th>볼넷</th><th>삼진</th></tr></thead><tbody>{items.slice(0,5).map((p:any)=><tr key={p.name} className="border-t border-slate-800"><td className="py-3 font-black">{p.name}</td><td>{p.wins}-{p.losses}</td><td>{p.innings}</td><td>{fmt(p.era,2)}</td><td>{fmt(p.whip,2)}</td><td>{p.walks}</td><td>{p.strikeouts}</td></tr>)}</tbody></table>{items.length===0&&<p className="py-5 text-slate-500">투수 기록을 불러오지 못했습니다.</p>}</div>}
function TeamPanel({name,standing,batting,pitching,side}:{name:string;standing:any;batting:any;pitching:any;side:"home"|"away"}){return <Card title={side==="home"?"홈팀 종합 기록":"원정팀 종합 기록"}><h2 className="mt-2 text-xl font-black">{name}</h2><div className="mt-4 grid grid-cols-2 gap-3"><Metric label="순위" value={standing?`${standing.rank}위`:"-"}/><Metric label="승률" value={fmt(standing?.winningPercentage)}/><Metric label="시즌 성적" value={standing?`${standing.wins}승 ${standing.losses}패 ${standing.draws}무`:"-"}/><Metric label={side==="home"?"홈 성적":"원정 성적"} value={"공식 자료 미제공"}/><Metric label="팀 타율" value={fmt(batting?.average)}/><Metric label="팀 OPS" value={fmt(batting?.ops)}/><Metric label="홈런 / 볼넷" value={batting?`${batting.homeRuns} / ${batting.walks}`:"-"}/><Metric label="팀 삼진" value={batting?.strikeouts??"-"}/><Metric label="팀 ERA" value={fmt(pitching?.era,2)}/><Metric label="팀 WHIP" value={fmt(pitching?.whip,2)}/></div></Card>}
function Content(){const q=useSearchParams(),away=q.get("away")||"원정팀",home=q.get("home")||"홈팀",date=q.get("date")||"",time=q.get("time")||"",stadium=q.get("stadium")||"",awayStarter=q.get("awayStarter")||"",homeStarter=q.get("homeStarter")||"";const[d,setD]=useState<any>(null),[err,setErr]=useState("");useEffect(()=>{setErr("");fetch(`/api/npb/analysis?away=${encodeURIComponent(away)}&home=${encodeURIComponent(home)}&date=${date}`,{cache:"no-store"}).then(r=>r.json()).then(x=>x.success?setD(x):setErr(x.message||"분석 오류")).catch(e=>setErr(e.message))},[away,home,date]);
 return <main className="min-h-screen bg-slate-950 text-white"><header className="border-b border-slate-800"><div className="mx-auto flex max-w-6xl justify-between px-5 py-5"><Link href="/" className="text-2xl font-black">Sports AI</Link><Link href="/" className="text-sm font-black text-blue-400">← 경기 목록</Link></div></header><div className="mx-auto max-w-6xl px-5 py-10"><div className="rounded-3xl border border-slate-800 bg-slate-900 p-7"><p className="text-sm font-black text-blue-400">NPB 경기 상세 분석 · <span className="text-emerald-400">수정본 v3</span></p><h1 className="mt-3 text-3xl font-black">{away} 대 {home}</h1><p className="mt-3 text-sm text-slate-400">{date} {time} · {stadium||"경기장 미정"} · 한국시간</p></div>{err&&<p className="mt-6 rounded-xl border border-red-900 bg-red-950/30 p-4 text-red-300">{err}</p>}{!d&&!err&&<p className="mt-6 text-slate-400">공식 기록을 불러와 분석 중입니다.</p>}
 <div className="mt-6 grid gap-5 md:grid-cols-2"><TeamPanel name={away} standing={d?.awayStanding} batting={d?.awayBatting} pitching={d?.awayPitching} side="away"/><TeamPanel name={home} standing={d?.homeStanding} batting={d?.homeBatting} pitching={d?.homePitching} side="home"/></div>
 <div className="mt-6"><Card title="AI 종합 분석"><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-slate-500">최종 추천</p><h2 className="mt-1 text-2xl font-black">{d?.pick||"분석 중"}</h2></div><p className="text-xl font-black text-blue-400">신뢰도 {d?.confidence??"-"}점</p></div>{d&&<><div className="mt-5 flex justify-between font-black"><span>{away} {d.probability.away}%</span><span>{home} {d.probability.home}%</span></div><div className="mt-3 flex h-4 overflow-hidden rounded-full bg-slate-800"><div className="bg-slate-500" style={{width:`${d.probability.away}%`}}/><div className="bg-blue-600" style={{width:`${d.probability.home}%`}}/></div><div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-4"><Metric label="시즌 전력" value={`${d.scores.season>0?"홈 +":"원정 +"}${Math.abs(d.scores.season)}`}/><Metric label="타선" value={`${d.scores.batting>0?"홈 +":"원정 +"}${Math.abs(d.scores.batting)}`}/><Metric label="투수력" value={`${d.scores.pitching>0?"홈 +":"원정 +"}${Math.abs(d.scores.pitching)}`}/><Metric label="홈·원정" value={`${d.scores.homeAway>0?"홈 +":"원정 +"}${Math.abs(d.scores.homeAway)}`}/></div><div className="mt-5 space-y-2 text-sm text-slate-400">{d.reasons.map((r:string,i:number)=><p key={i}>• {r}</p>)}</div></>}</Card></div>
 <div className="mt-6 grid gap-5 md:grid-cols-2"><Card title={`${away} 선발·로테이션`}><p className="mt-2 text-sm text-slate-400">공식 선발: <b className="text-white">{awayStarter||"미정"}</b></p><PitcherTable items={d?.awayRotation||[]}/></Card><Card title={`${home} 선발·로테이션`}><p className="mt-2 text-sm text-slate-400">공식 선발: <b className="text-white">{homeStarter||"미정"}</b></p><PitcherTable items={d?.homeRotation||[]}/></Card></div>
 <div className="mt-6 grid gap-5 md:grid-cols-2"><Card title={`${away} 불펜 핵심`}><PitcherTable items={d?.awayBullpen||[]}/></Card><Card title={`${home} 불펜 핵심`}><PitcherTable items={d?.homeBullpen||[]}/></Card></div>
 <div className="mt-6"><Card title="아직 연결되지 않은 항목"><p className="mt-3 text-sm leading-7 text-slate-400">최근 5·10경기, 상대전적, 선발의 상대팀·구장별 성적, 최근 3일 불펜 투구 수, 날씨와 심판은 다음 단계에서 경기별 기록 소스를 연결해야 합니다. 현재 화면에는 공식 시즌 기록만 표시합니다.</p></Card></div></div></main>}
export default function Page(){return <Suspense fallback={<main className="min-h-screen bg-slate-950 p-10 text-white">불러오는 중...</main>}><Content/></Suspense>}
